apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: operatorsdk-memcached
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operatorsdk-memcached
  name: memcached-sample
spec:
  size: 2
  # TODO(user): Add fields here
